### ISSUE TITLE
Tower of Fame

### ISSUE THREAD

**Issue by aproje** [tatool/tatool-web#97] opened 2017-11-22 15:01 UTC
Hello!

For our project we want to use German and English versions of the Tower of Fame. I have some concerns:

1. Where can I get the stimuli text for English translation? I couldn't find them here (tatool-web-master/app/projects/public/uzh-multi-battery/stimuli), or am I looking at the wrong place? Please advise.
 
2. I recreated the German Tower of Fame using tatool Editor but the stimuli text came out without spaces between words (see attached). How can I fix this?

Thanks
Kith
![german tower of fame](https://user-images.githubusercontent.com/33902157/33133828-48752408-cf9e-11e7-8b84-645148627e2a.jpg)

**Comment by alocher** [comment] 2017-11-22 17:07
Hi Kith,

1) The TowerOfFame task (test/training) has a "displayLanguage" property (see http://www.tatool-web.com/#/doc/lib-bat-uzh-multi-testing.html). You can set this to "DE" for German and "EN" for English. As you can see the instructions (de_tower/de_training_tower) haven't been translated to English yet. You can find the relevant files here: https://github.com/tatool/tatool-web/tree/master/app/projects/public/uzh-multi-battery/instructions
Do you by any chance have some time to do the translation? That would be great and we could obviously host them for eveyone afterwards :)

2) That looks weird indeed. Can you tell me what OS/Browser (incl. version) you're using? Can you make sure this also happens when you create a module using the "official" json file?(https://raw.githubusercontent.com/tatool/tatool-web/master/app/projects/public/uzh-multi-battery/modules/de_multi_testing.json)

**Comment by aproje** [comment] 2017-11-29 08:42
Hi Andre

1. I already translated the instructions, but I also need to translate the stimuli text (ex. David Beckham lives in 4c. Paris Hilton lives on the same floor as David Beckham in the apartment diagonally opposite.). This is what I'm looking for which I couldn't find in github. Do you know where I can find them? After I'm done with the translation, I'll definitely send them to you. :)

2. I'm using google Chrome Version 62.0.3202.94 (64-Bit). I only use tatool Editor for module creation, so I haven't used the official json file.

**Comment by aproje** [comment] 2017-11-29 12:25
Hi again

I just edited our German Tower of Fame using tatool Editor, but I unfortunately cannot go beyond the 1st practice round. Clicking on the floor and unit doesn't work, neither does the next button. Could you please help?

**Comment by alocher** [comment] 2017-11-29 12:53
As for the language: have you tried switching the task with the displayLanguage property as described in my answer above?

Are you still experiencing the issue described in 2? What OS and screen resolution are you using? Would you mind using the Module json provided here http://www.tatool-web.com/#/doc/lib-bat-uzh-multi-testing.html to create a new module and test whether it happens as well?

I just noticed that the towerOfFame task hasn't updated properly with the latest release. I've reuploaded and the issue should be gone now after a refresh.

**Comment by aproje** [comment] 2017-11-29 14:57
Yes, I've changed the displayLanguage property, so the practice round and actual test are now available in English -  thanks so much and sorry about missing that.  Is it ok if I send you the English instructions as an attachment here? Is Powerpoint ok or do you prefer Word?

Yes, I'm still experiencing issue #2. I'm using Windows 10 Pro with a 1920 x 1080 resolution. When I create a new module using the json, everything is normal. I added the Tower of Fame at the very end of our cognitive test, which is a series of executive function and working memory tasks. Prior to the Tower of Fame, I already put together about 7 tasks. Could it be because of that?

**Comment by alocher** [comment] 2017-11-29 15:08
Great, I'm glad the language works now. You can just email us a powerpoint, that's fine.

You're probably right regarding the display issue being caused by the sequence of tasks. I've made sure that the css (style) classes are unique for the toweroffame. Can you refresh and give it another try? Can you maybe also let me know what other tasks you're using? Thanks.

**Comment by aproje** [comment] 2017-11-29 16:12
Here's the list of our tasks:

Executive Functions
1.) Inhibition: Simon, Flanker, Stroop
2.) Switching / Shifting: Shape / Color (5 parts) & Parity / Magnitude (combined task)
3.) Updating: Letter Task

Working Memory
4.) Storage and Processing: Brown-Peterson Task
5.) Relational Integration: Tower of Fame Task

The English Tower of Fame (with German instructions) looks good now after you refreshed it. I assume the German one should be ok too. 

I attached the English instructions. Each slide corresponds with the German html instructions, except the last one (slide 14), which is the break. The original German instructions are in the notes below each slide. One more thing, I purposely didn't translate one sentence on slide 13 (If you have any questions, please ask your experimenter now.) because it's not relevant to us. You might want to include that. Hope this helps!
[Tower of Fame.pptx](https://github.com/tatool/tatool-web/files/1514469/Tower.of.Fame.pptx)

**Comment by alocher** [comment] 2017-11-29 17:28
That's good news, it must have been caused by some odd override of classes. I'll close the issue tomorrow unless you still find an issue.

I've also uploaded your translated instructions, thanks again!

**Closed** 2017-12-01 08:53 UTC
Labels: Question
